name: Example
on:
  - pull_request

permissions:
  contents: read

jobs:
  example:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: test
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./
