name: Example
on:
  - pull_request

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  example:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./
